"""Parse canonical instructions and manage generated adapter files."""

from __future__ import annotations

import re
from pathlib import Path

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)

FALLBACK_DESCRIPTION = "Use this {kind} for {name} related work."

GENERATED_COMMENT = """\
<!--
This file is generated by tools/skills.
Do not edit this file directly.
Edit .ai/{source_kind}/{name}.md and run `make generate-ai`.
-->
"""

MARKDOWN_HEADER = """\
---
name: {name}
description: {description}
generated: true
source: .ai/{source_kind}/{name}.md
---
"""

# ---------------------------------------------------------------------------
# Frontmatter helpers
# ---------------------------------------------------------------------------


def _parse_frontmatter_block(block: str) -> dict[str, object]:
    fields: dict[str, object] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, _, raw_value = stripped.partition(":")
        key = key.strip()
        value = raw_value.strip()
        if not key:
            continue
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        lowered = value.lower()
        if lowered == "true":
            fields[key] = True
        elif lowered == "false":
            fields[key] = False
        else:
            fields[key] = value
    return fields


def split_instruction_content(text: str) -> tuple[dict[str, object], str]:
    """Return frontmatter fields and body (without the source frontmatter block)."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    fields = _parse_frontmatter_block(match.group(1))
    body = text[match.end() :]
    if body.startswith("\n"):
        body = body[1:]
    return fields, body


# Backward-compatible alias used by existing tests.
split_skill_content = split_instruction_content


def parse_frontmatter(text: str) -> dict[str, object]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    return _parse_frontmatter_block(match.group(1))


def is_generated(path: Path) -> bool:
    try:
        generated = parse_frontmatter(path.read_text()).get("generated")
    except OSError:
        return False
    if generated is True:
        return True
    return isinstance(generated, str) and generated.lower() == "true"


def yaml_scalar(value: str) -> str:
    if not value:
        return '""'
    if re.search(r'[:#\[\]{}"\'\\,&*!|>%@`]', value) or value.strip() != value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


# ---------------------------------------------------------------------------
# Source reader
# ---------------------------------------------------------------------------


def read_source(path: Path, *, kind: str) -> tuple[str, str, str]:
    """Return (name, description, body) for a canonical .ai/ instruction file."""
    text = path.read_text()
    fields, body = split_instruction_content(text)
    name = str(fields.get("name") or path.stem)
    description = str(
        fields.get("description") or FALLBACK_DESCRIPTION.format(kind=kind, name=name)
    )
    return name, description, body


def build_adapter(header: str, *, name: str, description: str, body: str, source_kind: str) -> str:
    comment = GENERATED_COMMENT.format(name=name, source_kind=source_kind)
    rendered_header = header.format(
        name=name,
        description=yaml_scalar(description),
        source_kind=source_kind,
    )
    if body:
        return f"{rendered_header}\n{comment}\n{body}"
    return f"{rendered_header}\n{comment}\n"


def write_adapter(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def remove_generated(path: Path, removed: list[Path]) -> None:
    if is_generated(path):
        path.unlink()
        removed.append(path)


def remove_if_empty(path: Path, removed: list[Path]) -> None:
    if path.exists() and path.is_dir() and not any(path.iterdir()):
        path.rmdir()
        removed.append(path)


def remove_stale_in(adapter_dir: Path, source_names: set[str], removed: list[Path]) -> None:
    if not adapter_dir.exists():
        return
    for f in list(adapter_dir.glob("*.md")) + list(adapter_dir.glob("*.mdc")):
        if f.stem not in source_names:
            remove_generated(f, removed)
